---
functional
  - В чатах пользователей есть список пользоватлей,логика работы чата,тесты,отображается автор сообщения
  - Пользователь должен иметь возможность измененть синтаксис языка в редакторе
  - Пользователь должен иметь  возможность сдаться в игре и соответствующая кнопка 
  - Пользователю должен быть виден статус игры
  - У пользователя есть возможность играть с ботом,другими пользователями,друзьями
  - У пользователя есть возможность выбора уровня сложности задачи, доступны 4 сложности: elementary, easy, medium, hard
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Кнопка создания игры подсвечена зеленым цветом
  - Кнопка Fith,Show подсвечена красной каймой
  - Шапка сайта оформлена черным цветом и белым текстом на ней
